[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22.19.0"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"