name: release-please
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: invoice-maker-app
          bump-minor-pre-major: true
          changelog-types: >
            [{"type":"feat","section":"Features"},
             {"type":"fix","section":"Bug Fixes"},
             {"type":"perf","section":"Performance"},
             {"type":"refactor","section":"Refactors"},
             {"type":"docs","section":"Docs"},
             {"type":"chore","section":"Chores"}]